/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
import java.sql.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
public class Ed_Publisher extends javax.swing.JInternalFrame {

    /**
     * Creates new form Ed_Author
     */
    public Ed_Publisher() {
        initComponents();
        pan2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan1 = new javax.swing.JPanel();
        lb1 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox<>();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pan2 = new javax.swing.JPanel();
        lb6 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        bt6 = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        tf2 = new javax.swing.JTextField();
        lb3 = new javax.swing.JLabel();
        lb7 = new javax.swing.JLabel();
        lb8 = new javax.swing.JLabel();
        tf6 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        tf5 = new javax.swing.JTextField();
        lb4 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();
        tf7 = new javax.swing.JTextField();
        tf1 = new javax.swing.JLabel();
        lb = new javax.swing.JLabel();

        pan1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lb1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb1.setText("Publisher Name :");

        cb1.setModel(new javax.swing.DefaultComboBoxModel());
        cb1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cb1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cb1FocusLost(evt);
            }
        });

        bt1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bt1.setForeground(new java.awt.Color(0, 0, 153));
        bt1.setText("EDIT");
        bt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt1MouseExited(evt);
            }
        });
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });

        bt2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bt2.setForeground(new java.awt.Color(0, 0, 153));
        bt2.setText("CLOSE");
        bt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt2MouseExited(evt);
            }
        });
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan1Layout = new javax.swing.GroupLayout(pan1);
        pan1.setLayout(pan1Layout);
        pan1Layout.setHorizontalGroup(
            pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan1Layout.createSequentialGroup()
                .addGap(0, 104, Short.MAX_VALUE)
                .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pan1Layout.createSequentialGroup()
                        .addComponent(bt1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt2))
                    .addGroup(pan1Layout.createSequentialGroup()
                        .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        pan1Layout.setVerticalGroup(
            pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt1)
                    .addComponent(bt2))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pan2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb6.setText("PUBLISHER  NO.     :");
        pan2.add(lb6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 190, -1));

        lb2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb2.setText("PUBLISHER NAME :");
        pan2.add(lb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 180, -1));

        bt6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bt6.setForeground(new java.awt.Color(0, 0, 102));
        bt6.setText("SAVE");
        bt6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt6MouseExited(evt);
            }
        });
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });
        pan2.add(bt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, -1, -1));

        bt7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bt7.setForeground(new java.awt.Color(0, 0, 102));
        bt7.setText("CLEAR");
        bt7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt7MouseExited(evt);
            }
        });
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });
        pan2.add(bt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, -1, -1));

        bt3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bt3.setForeground(new java.awt.Color(0, 0, 102));
        bt3.setText("CLOSE");
        bt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt3MouseExited(evt);
            }
        });
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        pan2.add(bt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, -1, -1));

        tf2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tf2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf2FocusGained(evt);
            }
        });
        tf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2ActionPerformed(evt);
            }
        });
        tf2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf2KeyTyped(evt);
            }
        });
        pan2.add(tf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 240, 30));

        lb3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb3.setText("ADDRESS :");
        pan2.add(lb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 110, -1));

        lb7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb7.setText("e-mail :");
        pan2.add(lb7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 70, -1));

        lb8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb8.setText("twitter :");
        pan2.add(lb8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 70, -1));

        tf6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tf6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf6FocusGained(evt);
            }
        });
        tf6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf6KeyTyped(evt);
            }
        });
        pan2.add(tf6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 240, 30));

        tf4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tf4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf4FocusGained(evt);
            }
        });
        tf4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf4KeyTyped(evt);
            }
        });
        pan2.add(tf4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 240, 30));

        tf3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tf3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf3FocusGained(evt);
            }
        });
        tf3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf3KeyTyped(evt);
            }
        });
        pan2.add(tf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 240, 30));

        tf5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tf5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf5FocusGained(evt);
            }
        });
        tf5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf5KeyTyped(evt);
            }
        });
        pan2.add(tf5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 240, 30));

        lb4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb4.setText("CITY :");
        pan2.add(lb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 110, -1));

        lb5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb5.setText("MOBILE :");
        pan2.add(lb5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 110, -1));

        tf7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tf7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf7FocusGained(evt);
            }
        });
        tf7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf7KeyTyped(evt);
            }
        });
        pan2.add(tf7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 240, 30));

        tf1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tf1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tf1.setOpaque(true);
        pan2.add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 60, 30));

        lb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Nature7.jpg"))); // NOI18N
        pan2.add(lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 470));

        jScrollPane1.setViewportView(pan2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(pan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cb1FocusGained

        Connection con = null;
        ResultSet rs =  null;
        Statement st = null;
        String sql="";
        
        DefaultComboBoxModel dm = (DefaultComboBoxModel)cb1.getModel();
        
        try
        {
            try
            {
                  Class.forName("java.sql.Driver");
                  con = DriverManager.getConnection(Login.URL,Login.URS,Login.PAS);
                  st = con.createStatement();
                  
                  sql = "select pubnm from publisher order by pubnm";
                  rs = st.executeQuery(sql);
                  
                  dm.removeAllElements();
                  dm.addElement("--select--");
                  while(rs.next())
                       dm.addElement(rs.getString("pubnm"));
            }
            catch(Exception e)
            {
                  JOptionPane.showMessageDialog(null,"ERROR : "+e.getMessage());
            }
        }
        catch(Exception e)
        {
              JOptionPane.showMessageDialog(null,"ERROR : "+e.getMessage());
        }
    }//GEN-LAST:event_cb1FocusGained

    private void cb1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cb1FocusLost
       /* Connection con = null;
        ResultSet rs =  null;
        Statement st = null;
        String sql="";
        
        try
        {
            try
            {
                  Class.forName("java.sql.Driver");
                  con = DriverManager.getConnection(Login.URL,Login.URS,Login.PAS);
                  st = con.createStatement();
                  
                  sql = "select pubno from publisher where pubnm = '"+cb1.getSelectedItem()+"';";
                  rs = st.executeQuery(sql);
                  if(rs.next())
                      tf1.setText(rs.getInt("pubno")+"");
                  
            }
            catch(Exception e)
            {
                  JOptionPane.showMessageDialog(null,"ERROR : "+e.getMessage());
            }
        }
        catch(Exception e)
        {
              JOptionPane.showMessageDialog(null,"ERROR : "+e.getMessage());
        }*/
    }//GEN-LAST:event_cb1FocusLost

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
       this.dispose();
       new Main().setVisible(true);
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt1MouseEntered
        bt1.setBackground(java.awt.Color.BLACK);
        bt1.setForeground(java.awt.Color.ORANGE);
    }//GEN-LAST:event_bt1MouseEntered

    private void bt1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt1MouseExited
        bt1.setBackground(java.awt.Color.WHITE);
        bt1.setForeground(java.awt.Color.BLUE);
    }//GEN-LAST:event_bt1MouseExited

    private void bt2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt2MouseEntered
         bt2.setBackground(java.awt.Color.BLACK);
         bt2.setForeground(java.awt.Color.ORANGE);
    }//GEN-LAST:event_bt2MouseEntered

    private void bt2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt2MouseExited
        bt2.setBackground(java.awt.Color.WHITE);
        bt2.setForeground(java.awt.Color.BLUE);
    }//GEN-LAST:event_bt2MouseExited

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
       pan2.setVisible(true);
       
       Connection con = null;
       ResultSet rs = null;
       Statement st = null ;
       String sql = "";
       
       try
       {
           try
           {
                  Class.forName("java.sql.Driver");
                  con = DriverManager.getConnection(Login.URL,Login.URS,Login.PAS);
                  st = con.createStatement();
                  
                  sql = "Select * from publisher where pubnm = '"+cb1.getSelectedItem()+"';";
                  rs = st.executeQuery(sql);
                  
                  if(rs.next())
                  {
                        tf1.setText(rs.getInt(1)+"");
                        tf2.setText(rs.getObject(2)+"");
                        tf3.setText(rs.getObject(3)+"");
                        tf4.setText(rs.getObject(4)+"");   
                        tf5.setText(rs.getObject(5)+"");   
                        tf6.setText(rs.getObject(6)+"");   
                        tf7.setText(rs.getObject(7)+"");   
                  }
           }
           catch(Exception e)
           {
                  JOptionPane.showMessageDialog(null,"ERROR : "+e.getMessage());
           }
       }
       catch(Exception e)
       {
             JOptionPane.showMessageDialog(null,"ERROR : "+e.getMessage());
       }
       tf2.requestFocus();
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt6MouseEntered
        bt6.setBackground(java.awt.Color.BLACK);
        bt6.setForeground(java.awt.Color.ORANGE);
    }//GEN-LAST:event_bt6MouseEntered

    private void bt6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt6MouseExited
        bt6.setBackground(java.awt.Color.WHITE);
        bt6.setForeground(java.awt.Color.BLUE);
    }//GEN-LAST:event_bt6MouseExited

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
        Connection con = null;
        Statement st = null ;
        String sql = "";

        try
        {
            try
            {
                Class.forName("java.sql.Driver");
                con = DriverManager.getConnection(Login.URL,Login.URS,Login.PAS);
                st = con.createStatement();

                sql = "update publisher set pubnm ='"+tf2.getText()+"', addr ='"+
                tf3.getText()+"',city = '"+tf4.getText()+"', mob = '"+tf5.getText()
                +"', email = '"+tf6.getText()+"',twit = '"+tf7.getText()+"' where pubno = "+
                        tf1.getText()+";";

                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"PUBLISHER EDITED!!");
                this.bt7.doClick();

            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"ERROR : "+e.getMessage());
            }
            finally
            {
                if(!con.isClosed())
                con.close();
                if(!st.isClosed())
                st.close();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"ERROR : "+e.getMessage());
        }
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt7MouseEntered
        bt7.setBackground(java.awt.Color.BLACK);
        bt7.setForeground(java.awt.Color.ORANGE);
    }//GEN-LAST:event_bt7MouseEntered

    private void bt7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt7MouseExited
        bt7.setBackground(java.awt.Color.WHITE);
        bt7.setForeground(java.awt.Color.BLUE);
    }//GEN-LAST:event_bt7MouseExited

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed

        tf2.setText("");
        tf3.setText("");
        tf4.setText("");
        tf5.setText("");
        tf6.setText("");
        tf7.setText("");
        tf2.requestFocus();
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt3MouseEntered
        bt3.setBackground(java.awt.Color.BLACK);
        bt3.setForeground(java.awt.Color.ORANGE);
    }//GEN-LAST:event_bt3MouseEntered

    private void bt3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt3MouseExited
        bt3.setBackground(java.awt.Color.WHITE);
        bt3.setForeground(java.awt.Color.BLUE);
    }//GEN-LAST:event_bt3MouseExited

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        this.dispose();
        new Main().setVisible(true);
    }//GEN-LAST:event_bt3ActionPerformed

    private void tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf2ActionPerformed

    private void tf2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf2KeyTyped
        char ch = evt.getKeyChar();
        if(ch == '\n')
        {
            tf2.setText(En_Almirah.toTitleCase(tf2.getText()));
            tf3.requestFocus();
        }
    }//GEN-LAST:event_tf2KeyTyped

    private void tf6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf6KeyTyped
        char ch = evt.getKeyChar();
        if(ch == '\n')
        {
            tf6.setText(tf6.getText().toLowerCase());
            tf7.requestFocus();
        }
    }//GEN-LAST:event_tf6KeyTyped

    private void tf4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf4KeyTyped
        char ch = evt.getKeyChar();
        if(ch == '\n')
        {
            tf4.setText(En_Almirah.toTitleCase(tf4.getText()));
            tf5.requestFocus();
        }
    }//GEN-LAST:event_tf4KeyTyped

    private void tf3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf3KeyTyped
        char ch = evt.getKeyChar();
        if(ch == '\n')
        {
            tf3.setText(En_Almirah.toTitleCase(tf3.getText()));
            tf4.requestFocus();
        }
    }//GEN-LAST:event_tf3KeyTyped

    private void tf5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf5KeyTyped
        char ch = evt.getKeyChar();
        if(ch == '\n')
        tf6.requestFocus();

    }//GEN-LAST:event_tf5KeyTyped

    private void tf7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf7KeyTyped
        char ch = evt.getKeyChar();
        if(ch == '\n')
        {
            tf7.setText(tf7.getText().toLowerCase());
            bt6.doClick();
        }
    }//GEN-LAST:event_tf7KeyTyped

    private void tf2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf2FocusGained
        tf2.selectAll();
    }//GEN-LAST:event_tf2FocusGained

    private void tf3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf3FocusGained
       tf3.selectAll();
    }//GEN-LAST:event_tf3FocusGained

    private void tf4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf4FocusGained
        tf4.selectAll();
    }//GEN-LAST:event_tf4FocusGained

    private void tf5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf5FocusGained
        tf5.selectAll();
    }//GEN-LAST:event_tf5FocusGained

    private void tf6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf6FocusGained
        tf6.selectAll();
    }//GEN-LAST:event_tf6FocusGained

    private void tf7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf7FocusGained
        tf7.selectAll();
    }//GEN-LAST:event_tf7FocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel lb6;
    private javax.swing.JLabel lb7;
    private javax.swing.JLabel lb8;
    private javax.swing.JPanel pan1;
    private javax.swing.JPanel pan2;
    private javax.swing.JLabel tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    private javax.swing.JTextField tf6;
    private javax.swing.JTextField tf7;
    // End of variables declaration//GEN-END:variables
}
