/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
import java.sql.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
public class En_Shelf extends javax.swing.JInternalFrame {

    /**
     * Creates new form En_Shelf
     */
    boolean flag = false;
    public En_Shelf() {
        initComponents();
        
        flag = true;
        populate();
        flag = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cb1 = new javax.swing.JComboBox<>();
        lb1 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        lb4 = new javax.swing.JLabel();
        lb = new javax.swing.JLabel();

        setTitle("Shelf Enteries");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cb1.setBackground(new java.awt.Color(240, 240, 240));
        cb1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cb1.setModel(new javax.swing.DefaultComboBoxModel());
        cb1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb1ItemStateChanged(evt);
            }
        });
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        jPanel1.add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 220, 30));

        lb1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb1.setText("ALMIRAH NAME   :");
        jPanel1.add(lb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 200, -1));

        lb3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lb3.setOpaque(true);
        jPanel1.add(lb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 220, 30));

        lb2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb2.setText("SHELF NUMBER   :");
        jPanel1.add(lb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 200, -1));

        bt1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bt1.setForeground(new java.awt.Color(0, 0, 102));
        bt1.setText("SAVE");
        bt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt1MouseExited(evt);
            }
        });
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        jPanel1.add(bt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 187, -1, -1));

        bt2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bt2.setForeground(new java.awt.Color(0, 0, 102));
        bt2.setText("CLEAR");
        bt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt2MouseExited(evt);
            }
        });
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        jPanel1.add(bt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 187, -1, -1));

        bt3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bt3.setForeground(new java.awt.Color(0, 0, 102));
        bt3.setText("CLOSE");
        bt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt3MouseExited(evt);
            }
        });
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        jPanel1.add(bt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 187, -1, -1));

        lb4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lb4.setOpaque(true);
        jPanel1.add(lb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 60, 30));

        lb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Nature7.jpg"))); // NOI18N
        jPanel1.add(lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void populate()
    {
         DefaultComboBoxModel dm = (DefaultComboBoxModel) cb1.getModel();
         
         dm.removeAllElements();
         
         Connection con = null;
         ResultSet rs= null;
         Statement st = null;
         String sql="";
         
         try
         {
              try
              {
                      Class.forName("java.sql.Driver");
                      con = DriverManager.getConnection(Login.URL,Login.URS,Login.PAS);
                      st = con.createStatement();
                      
                      sql = "select alnm from almirah order by alnm ";
                      rs= st.executeQuery(sql);
                      
                      dm.addElement("-- select --");
                      while(rs.next())
                          dm.addElement(rs.getString("alnm"));
                      
              }
              catch(Exception e)
              {
                    JOptionPane.showMessageDialog(null,"ERROR : "+e.getMessage());
              }
              finally
              {
                    if(!con.isClosed())
                         con.close();
                    if(!rs.isClosed())
                         rs.close();
                    if(!st.isClosed())
                         st.close();
              }
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(null,"ERROR : "+e.getMessage());
         }
         
    }
    
    private void cal_shno()
    {
          Connection con = null;
          Statement st = null;
          ResultSet rs =  null;
          String sql = "";
          
          try
          {
               try
               { 
                     Class.forName("java.sql.Driver");
                     con= DriverManager.getConnection(Login.URL,Login.URS,Login.PAS);
                     st = con.createStatement();
                     
                     sql = "select max(shno) as mx from Shelf where alno = "+lb4.getText()+";";
                     rs = st.executeQuery(sql);
                     
                     if(rs.next())
                         lb3.setText(rs.getInt("mx")+1+"");
                     else
                         lb3.setText("1");
               }
               catch(Exception e)
               {
                     JOptionPane.showMessageDialog(null,"ERROR : "+e.getMessage());
               }
          }
          catch(Exception e)
          {
                 JOptionPane.showMessageDialog(null,"ERROR : "+e.getMessage());
          }
    }
    private void bt1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt1MouseEntered
        bt1.setBackground(java.awt.Color.BLACK);
        bt1.setForeground(java.awt.Color.ORANGE);
    }//GEN-LAST:event_bt1MouseEntered

    private void bt1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt1MouseExited
        bt1.setBackground(java.awt.Color.WHITE);
        bt1.setForeground(java.awt.Color.BLUE);
    }//GEN-LAST:event_bt1MouseExited

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        Connection con = null;
        Statement st = null ;
        String sql = "";

        try
        {
            try
            {
                Class.forName("java.sql.Driver");
                con = DriverManager.getConnection(Login.URL,Login.URS,Login.PAS);
                st = con.createStatement();

                sql = "insert into Shelf values("+lb4.getText()+","+lb3.getText()+");";

                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"SHELF ADDED!!");
                this.bt2.doClick();

            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"ERROR : "+e.getMessage());
            }
            finally
            {
                if(!con.isClosed())
                    con.close();
                if(!st.isClosed())
                    st.close();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"ERROR : "+e.getMessage());
        }
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt2MouseEntered
        bt2.setBackground(java.awt.Color.BLACK);
        bt2.setForeground(java.awt.Color.ORANGE);
    }//GEN-LAST:event_bt2MouseEntered

    private void bt2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt2MouseExited
        bt2.setBackground(java.awt.Color.WHITE);
        bt2.setForeground(java.awt.Color.BLUE);
    }//GEN-LAST:event_bt2MouseExited

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed

        flag = true;
        populate();
        flag = false;
        
        lb3.setText("");
        lb4.setText("");
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt3MouseEntered
        bt3.setBackground(java.awt.Color.BLACK);
        bt3.setForeground(java.awt.Color.ORANGE);
    }//GEN-LAST:event_bt3MouseEntered

    private void bt3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt3MouseExited
        bt3.setBackground(java.awt.Color.WHITE);
        bt3.setForeground(java.awt.Color.BLUE);
    }//GEN-LAST:event_bt3MouseExited

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        this.dispose();
        new Main().setVisible(true);
    }//GEN-LAST:event_bt3ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        
    }//GEN-LAST:event_cb1ActionPerformed

    private void cb1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb1ItemStateChanged
            if(this.cb1.getSelectedIndex() == 0 || flag==true )
                 return;
            
            Connection con = null;
            ResultSet rs = null;
            Statement st = null;
            String sql = "";
            
            try 
            {
                try 
                {
                       Class.forName("java.sql.Driver");
                       con = DriverManager.getConnection(Login.URL,Login.URS,Login.PAS);
                       st = con.createStatement();
                       
                       sql = "select alno from almirah where alnm = '"+cb1.getSelectedItem()+"';";
                       
                       rs = st.executeQuery(sql);
                       rs.next();
                            lb4.setText(rs.getInt("alno")+"");
                            
                }
                catch(Exception e)
                {
                      JOptionPane.showMessageDialog(null,"ERROR : "+e.getMessage());
                }
                finally
                {
                      if(!con.isClosed())
                            con.close();
                      if(!rs.isClosed())
                          rs.close();
                     if(!st.isClosed())
                         st.close();
                }
            }
            catch(Exception e)
            {
                  JOptionPane.showMessageDialog(null,"ERROR : "+e.getMessage());
            }
            cal_shno();
    }//GEN-LAST:event_cb1ItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    // End of variables declaration//GEN-END:variables
}
