/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpan = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem1 = new javax.swing.JMenuItem();
        saveAsMenuItem2 = new javax.swing.JMenuItem();
        saveAsMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        openMenuItem1 = new javax.swing.JMenuItem();
        saveMenuItem1 = new javax.swing.JMenuItem();
        saveAsMenuItem5 = new javax.swing.JMenuItem();
        saveAsMenuItem6 = new javax.swing.JMenuItem();
        saveAsMenuItem7 = new javax.swing.JMenuItem();
        saveAsMenuItem8 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        exitMenuItem1 = new javax.swing.JMenuItem();
        editMenu1 = new javax.swing.JMenu();
        openMenuItem2 = new javax.swing.JMenuItem();
        saveMenuItem2 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        exitMenuItem2 = new javax.swing.JMenuItem();
        fileMenu2 = new javax.swing.JMenu();
        openMenuItem4 = new javax.swing.JMenuItem();
        saveMenuItem4 = new javax.swing.JMenuItem();
        saveAsMenuItem12 = new javax.swing.JMenuItem();
        saveAsMenuItem13 = new javax.swing.JMenuItem();
        saveAsMenuItem14 = new javax.swing.JMenuItem();
        saveAsMenuItem15 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        exitMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Enteries");
        fileMenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        openMenuItem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Almirah");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        saveMenuItem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Shelf");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Author");
        saveAsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveAsMenuItem);

        saveAsMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveAsMenuItem1.setMnemonic('a');
        saveAsMenuItem1.setText("Publisher");
        saveAsMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItem1ActionPerformed(evt);
            }
        });
        fileMenu.add(saveAsMenuItem1);

        saveAsMenuItem2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveAsMenuItem2.setMnemonic('a');
        saveAsMenuItem2.setText("Book");
        saveAsMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItem2ActionPerformed(evt);
            }
        });
        fileMenu.add(saveAsMenuItem2);

        saveAsMenuItem3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveAsMenuItem3.setMnemonic('a');
        saveAsMenuItem3.setText("Member");
        saveAsMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItem3ActionPerformed(evt);
            }
        });
        fileMenu.add(saveAsMenuItem3);
        fileMenu.add(jSeparator1);

        exitMenuItem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");
        editMenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        openMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        openMenuItem1.setMnemonic('o');
        openMenuItem1.setText("Almirah");
        openMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItem1ActionPerformed(evt);
            }
        });
        editMenu.add(openMenuItem1);

        saveMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveMenuItem1.setMnemonic('s');
        saveMenuItem1.setText("Shelf");
        saveMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItem1ActionPerformed(evt);
            }
        });
        editMenu.add(saveMenuItem1);

        saveAsMenuItem5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveAsMenuItem5.setMnemonic('a');
        saveAsMenuItem5.setText("Author");
        saveAsMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItem5ActionPerformed(evt);
            }
        });
        editMenu.add(saveAsMenuItem5);

        saveAsMenuItem6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveAsMenuItem6.setMnemonic('a');
        saveAsMenuItem6.setText("Publisher");
        saveAsMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItem6ActionPerformed(evt);
            }
        });
        editMenu.add(saveAsMenuItem6);

        saveAsMenuItem7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveAsMenuItem7.setMnemonic('a');
        saveAsMenuItem7.setText("Book");
        saveAsMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItem7ActionPerformed(evt);
            }
        });
        editMenu.add(saveAsMenuItem7);

        saveAsMenuItem8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveAsMenuItem8.setMnemonic('a');
        saveAsMenuItem8.setText("Member");
        saveAsMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItem8ActionPerformed(evt);
            }
        });
        editMenu.add(saveAsMenuItem8);
        editMenu.add(jSeparator2);

        exitMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exitMenuItem1.setMnemonic('x');
        exitMenuItem1.setText("Exit");
        exitMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItem1ActionPerformed(evt);
            }
        });
        editMenu.add(exitMenuItem1);

        menuBar.add(editMenu);

        editMenu1.setMnemonic('e');
        editMenu1.setText("Transaction");
        editMenu1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        openMenuItem2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        openMenuItem2.setMnemonic('o');
        openMenuItem2.setText("Issue");
        openMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItem2ActionPerformed(evt);
            }
        });
        editMenu1.add(openMenuItem2);

        saveMenuItem2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveMenuItem2.setMnemonic('s');
        saveMenuItem2.setText("Return");
        saveMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItem2ActionPerformed(evt);
            }
        });
        editMenu1.add(saveMenuItem2);
        editMenu1.add(jSeparator3);

        exitMenuItem2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exitMenuItem2.setMnemonic('x');
        exitMenuItem2.setText("Exit");
        exitMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItem2ActionPerformed(evt);
            }
        });
        editMenu1.add(exitMenuItem2);

        menuBar.add(editMenu1);

        fileMenu2.setMnemonic('f');
        fileMenu2.setText("Show");
        fileMenu2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        openMenuItem4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        openMenuItem4.setMnemonic('o');
        openMenuItem4.setText("All book");
        openMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItem4ActionPerformed(evt);
            }
        });
        fileMenu2.add(openMenuItem4);

        saveMenuItem4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveMenuItem4.setMnemonic('s');
        saveMenuItem4.setText("Specfic book");
        saveMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItem4ActionPerformed(evt);
            }
        });
        fileMenu2.add(saveMenuItem4);

        saveAsMenuItem12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveAsMenuItem12.setMnemonic('a');
        saveAsMenuItem12.setText("All member");
        saveAsMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItem12ActionPerformed(evt);
            }
        });
        fileMenu2.add(saveAsMenuItem12);

        saveAsMenuItem13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveAsMenuItem13.setMnemonic('a');
        saveAsMenuItem13.setText("Specfic member");
        saveAsMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItem13ActionPerformed(evt);
            }
        });
        fileMenu2.add(saveAsMenuItem13);

        saveAsMenuItem14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveAsMenuItem14.setMnemonic('a');
        saveAsMenuItem14.setText("Issue book");
        saveAsMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItem14ActionPerformed(evt);
            }
        });
        fileMenu2.add(saveAsMenuItem14);

        saveAsMenuItem15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveAsMenuItem15.setMnemonic('a');
        saveAsMenuItem15.setText("History");
        saveAsMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItem15ActionPerformed(evt);
            }
        });
        fileMenu2.add(saveAsMenuItem15);
        fileMenu2.add(jSeparator5);

        exitMenuItem4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exitMenuItem4.setMnemonic('x');
        exitMenuItem4.setText("Exit");
        exitMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItem4ActionPerformed(evt);
            }
        });
        fileMenu2.add(exitMenuItem4);

        menuBar.add(fileMenu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpan, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpan, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        En_Almirah t  = new En_Almirah();
        dpan.add(t);
        t.setVisible(true);
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        En_Shelf t  = new En_Shelf();
        dpan.add(t);
        t.setVisible(true);
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void saveAsMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItem1ActionPerformed
        En_Publisher t  = new En_Publisher();
        dpan.add(t);
        t.setVisible(true);
    }//GEN-LAST:event_saveAsMenuItem1ActionPerformed

    private void openMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItem1ActionPerformed
        Ed_Almirah t = new Ed_Almirah();
        dpan.add(t);
        t.setVisible(true);
    }//GEN-LAST:event_openMenuItem1ActionPerformed

    private void saveMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItem1ActionPerformed
        Ed_Shelf t = new Ed_Shelf();
        dpan.add(t);
        t.setVisible(true);
    }//GEN-LAST:event_saveMenuItem1ActionPerformed

    private void saveAsMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItem6ActionPerformed
        Ed_Publisher t = new Ed_Publisher();
        dpan.add(t);
        t.setVisible(true);
    }//GEN-LAST:event_saveAsMenuItem6ActionPerformed

    private void exitMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitMenuItem1ActionPerformed

    private void saveAsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItemActionPerformed
        En_Author t  = new En_Author();
        dpan.add(t);
        t.setVisible(true);
    }//GEN-LAST:event_saveAsMenuItemActionPerformed

    private void saveAsMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItem3ActionPerformed
        En_Member t  = new En_Member();
        dpan.add(t);
        t.setVisible(true);
    }//GEN-LAST:event_saveAsMenuItem3ActionPerformed

    private void saveAsMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItem2ActionPerformed
        En_Book t = new En_Book();
        dpan.add(t);
        t.setVisible(true);
    }//GEN-LAST:event_saveAsMenuItem2ActionPerformed

    private void openMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItem2ActionPerformed
        Tr_Issue t = new Tr_Issue();
        dpan.add(t);
        t.setVisible(true);
    }//GEN-LAST:event_openMenuItem2ActionPerformed

    private void saveMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItem2ActionPerformed
        Tr_Return t = new Tr_Return();
        dpan.add(t);
        t.setVisible(true);
    }//GEN-LAST:event_saveMenuItem2ActionPerformed

    private void exitMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitMenuItem2ActionPerformed

    private void saveAsMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItem5ActionPerformed
        Ed_Author t  = new Ed_Author();
        dpan.add(t);
        t.setVisible(true);
    }//GEN-LAST:event_saveAsMenuItem5ActionPerformed

    private void saveAsMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItem8ActionPerformed
        Ed_Member t  = new Ed_Member();
        dpan.add(t);
        t.setVisible(true);
    }//GEN-LAST:event_saveAsMenuItem8ActionPerformed

    private void saveAsMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItem7ActionPerformed
        Ed_Book t  = new Ed_Book();
        dpan.add(t);
        t.setVisible(true);
    }//GEN-LAST:event_saveAsMenuItem7ActionPerformed

    private void openMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItem4ActionPerformed
        Sh_allBook t = new Sh_allBook();
        dpan.add(t);
        t.setVisible(true);
    }//GEN-LAST:event_openMenuItem4ActionPerformed

    private void saveMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItem4ActionPerformed
        Sh_spBook t = new Sh_spBook();
        dpan.add(t);
        t.setVisible(true);
    }//GEN-LAST:event_saveMenuItem4ActionPerformed

    private void saveAsMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItem12ActionPerformed
        Sh_allMem t = new Sh_allMem();
        dpan.add(t);
        t.setVisible(true);
    }//GEN-LAST:event_saveAsMenuItem12ActionPerformed

    private void saveAsMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItem13ActionPerformed
        Sh_spMem t = new Sh_spMem();
        dpan.add(t);
        t.setVisible(true);
    }//GEN-LAST:event_saveAsMenuItem13ActionPerformed

    private void saveAsMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItem14ActionPerformed
        Sh_Issue t = new Sh_Issue();
        dpan.add(t);
        t.setVisible(true);
    }//GEN-LAST:event_saveAsMenuItem14ActionPerformed

    private void saveAsMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuItem15ActionPerformed
        Sh_History t = new Sh_History();
        dpan.add(t);
        t.setVisible(true);
    }//GEN-LAST:event_saveAsMenuItem15ActionPerformed

    private void exitMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpan;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu editMenu1;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem exitMenuItem1;
    private javax.swing.JMenuItem exitMenuItem2;
    private javax.swing.JMenuItem exitMenuItem4;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu fileMenu2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem openMenuItem1;
    private javax.swing.JMenuItem openMenuItem2;
    private javax.swing.JMenuItem openMenuItem4;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem1;
    private javax.swing.JMenuItem saveAsMenuItem12;
    private javax.swing.JMenuItem saveAsMenuItem13;
    private javax.swing.JMenuItem saveAsMenuItem14;
    private javax.swing.JMenuItem saveAsMenuItem15;
    private javax.swing.JMenuItem saveAsMenuItem2;
    private javax.swing.JMenuItem saveAsMenuItem3;
    private javax.swing.JMenuItem saveAsMenuItem5;
    private javax.swing.JMenuItem saveAsMenuItem6;
    private javax.swing.JMenuItem saveAsMenuItem7;
    private javax.swing.JMenuItem saveAsMenuItem8;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JMenuItem saveMenuItem1;
    private javax.swing.JMenuItem saveMenuItem2;
    private javax.swing.JMenuItem saveMenuItem4;
    // End of variables declaration//GEN-END:variables

}
