/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
import java.sql.*;
import javax.swing.JOptionPane;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
public class Sh_allMem extends javax.swing.JInternalFrame {

    /**
     * Creates new form Sh_allMem
     */
    public Sh_allMem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        pan1 = new javax.swing.JPanel();
        lb1 = new javax.swing.JLabel();
        rb7 = new javax.swing.JRadioButton();
        rb8 = new javax.swing.JRadioButton();
        pan2 = new javax.swing.JPanel();
        lb2 = new javax.swing.JLabel();
        rb9 = new javax.swing.JRadioButton();
        rb10 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        pan1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pan1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb1.setForeground(new java.awt.Color(255, 204, 204));
        lb1.setText("Sorting Order : ");
        pan1.add(lb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 134, 24));

        buttonGroup1.add(rb7);
        rb7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rb7.setForeground(new java.awt.Color(255, 204, 204));
        rb7.setSelected(true);
        rb7.setText("Member no");
        pan1.add(rb7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 103, -1));

        buttonGroup1.add(rb8);
        rb8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rb8.setForeground(new java.awt.Color(255, 204, 204));
        rb8.setText("Member name");
        pan1.add(rb8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        pan2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lb2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb2.setForeground(new java.awt.Color(0, 0, 51));
        lb2.setText(" Order : ");

        buttonGroup2.add(rb9);
        rb9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rb9.setSelected(true);
        rb9.setText("Ascending");

        buttonGroup2.add(rb10);
        rb10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rb10.setText("Descending");

        javax.swing.GroupLayout pan2Layout = new javax.swing.GroupLayout(pan2);
        pan2.setLayout(pan2Layout);
        pan2Layout.setHorizontalGroup(
            pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lb2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rb9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(rb10, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        pan2Layout.setVerticalGroup(
            pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb9)
                    .addComponent(rb10))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pan1.add(pan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setForeground(new java.awt.Color(240, 240, 240));

        tb.setBackground(new java.awt.Color(51, 51, 51));
        tb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tb.setForeground(new java.awt.Color(240, 240, 240));
        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MNo", "MNane", "email", "Mobile", "Address", "Status"
            }
        ));
        jScrollPane1.setViewportView(tb);

        pan1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 650, 120));

        bt1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bt1.setForeground(new java.awt.Color(0, 0, 51));
        bt1.setText("SHOW");
        bt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt1MouseExited(evt);
            }
        });
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        bt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bt1KeyTyped(evt);
            }
        });
        pan1.add(bt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        bt2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bt2.setForeground(new java.awt.Color(0, 0, 51));
        bt2.setText("CLOSE");
        bt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt2MouseExited(evt);
            }
        });
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        pan1.add(bt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/0102_1024.jpg"))); // NOI18N
        pan1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt1MouseEntered
        bt1.setForeground(Color.ORANGE);
        bt1.setBackground(Color.BLACK);
    }//GEN-LAST:event_bt1MouseEntered

    private void bt1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt1MouseExited
        bt1.setForeground(Color.BLUE);
        bt1.setBackground(Color.WHITE);
    }//GEN-LAST:event_bt1MouseExited

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        Connection con = null;
        Statement st = null;
        ResultSet rs = null ;
        String sql = "";
        String sort = "order by ";
        String order = "asc";

        DefaultTableModel dm = (DefaultTableModel) tb.getModel();
        Object ob[]= new Object[6];

        try
        {
            try
            {
                Class.forName("java.sql.Driver");
                con = DriverManager.getConnection(Login.URL,Login.URS,Login.PAS);
                st = con.createStatement();

                
                if(rb7.isSelected())
                   sort+=" mno ";
                else if(rb8.isSelected())
                    sort+=" mnm ";

                if(rb9.isSelected())
                       ;
                else if(rb10.isSelected())
                order=" desc ";

                sql = "select * from Member "+sort+order+" ; ";

                rs = st.executeQuery(sql);

                dm.setRowCount(0);
                while(rs.next())
                {
                    ob[0] = rs.getObject(1);
                    ob[1] = rs.getObject(2);
                    ob[2] = rs.getObject(3);
                    ob[3] = rs.getObject(4);
                    ob[4] = rs.getObject(5);
                    ob[5] = rs.getObject(6);
                    
                    dm.addRow(ob);
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"ERROR  : "+e.getMessage());
            }
            finally
            {
                if(!con.isClosed())
                con.close();
                if(!rs.isClosed())
                rs.close();
                if(!st.isClosed())
                st.close();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"ERROR  : "+e.getMessage());
        }
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt1KeyTyped
        char ch = evt.getKeyChar();
        if(ch == '\n')
           bt1.doClick();
    }//GEN-LAST:event_bt1KeyTyped

    private void bt2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt2MouseEntered
        bt2.setForeground(Color.ORANGE);
        bt2.setBackground(Color.BLACK);
    }//GEN-LAST:event_bt2MouseEntered

    private void bt2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt2MouseExited
        bt2.setForeground(Color.BLUE);
        bt2.setBackground(Color.WHITE);
    }//GEN-LAST:event_bt2MouseExited

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        this.dispose();
        new Main().setVisible(true);
    }//GEN-LAST:event_bt2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JPanel pan1;
    private javax.swing.JPanel pan2;
    private javax.swing.JRadioButton rb10;
    private javax.swing.JRadioButton rb7;
    private javax.swing.JRadioButton rb8;
    private javax.swing.JRadioButton rb9;
    private javax.swing.JTable tb;
    // End of variables declaration//GEN-END:variables
}
