/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
import java.sql.*;
import javax.swing.JOptionPane;
public class Tr_Issue extends javax.swing.JInternalFrame {

    /**
     * Creates new form Tr_Issue
     */
    public Tr_Issue() {
        initComponents();
        pan2.setVisible(false);
        pan3.setVisible(false);
        pan4.setVisible(false);
        pan5.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        pan2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        bt3 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pan4 = new javax.swing.JPanel();
        lb3 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        tf6 = new javax.swing.JTextField();
        lb5 = new javax.swing.JLabel();
        lb6 = new javax.swing.JLabel();
        lb7 = new javax.swing.JLabel();
        lb8 = new javax.swing.JLabel();
        lb9 = new javax.swing.JLabel();
        tf5 = new javax.swing.JLabel();
        lb10 = new javax.swing.JLabel();
        lb11 = new javax.swing.JLabel();
        tf7 = new javax.swing.JLabel();
        tf11 = new javax.swing.JTextField();
        tf12 = new javax.swing.JTextField();
        tf13 = new javax.swing.JTextField();
        tf9 = new javax.swing.JLabel();
        tf10 = new javax.swing.JLabel();
        tf8 = new javax.swing.JLabel();
        lb = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pan5 = new javax.swing.JPanel();
        lb12 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        tf15 = new javax.swing.JTextField();
        lb13 = new javax.swing.JLabel();
        lb14 = new javax.swing.JLabel();
        tf19 = new javax.swing.JTextField();
        tf17 = new javax.swing.JTextField();
        tf16 = new javax.swing.JTextField();
        tf18 = new javax.swing.JTextField();
        lb15 = new javax.swing.JLabel();
        lb16 = new javax.swing.JLabel();
        tf14 = new javax.swing.JLabel();
        lb17 = new javax.swing.JLabel();
        tf20 = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        pan3 = new javax.swing.JPanel();
        tf4 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bt5 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));
        setTitle("ISSUE FORM");

        pan1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Book No.");

        tf1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tf1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf1KeyTyped(evt);
            }
        });

        bt1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt1.setForeground(new java.awt.Color(0, 0, 153));
        bt1.setText("ISSUE");
        bt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt1MouseExited(evt);
            }
        });
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });

        bt2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt2.setForeground(new java.awt.Color(0, 0, 153));
        bt2.setText("CLOSE");
        bt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt2MouseExited(evt);
            }
        });
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan1Layout = new javax.swing.GroupLayout(pan1);
        pan1.setLayout(pan1Layout);
        pan1Layout.setHorizontalGroup(
            pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pan1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pan1Layout.createSequentialGroup()
                        .addComponent(bt1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt2)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        pan1Layout.setVerticalGroup(
            pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt2)
                    .addComponent(bt1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pan2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Member No.");

        tf2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tf2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf2KeyTyped(evt);
            }
        });

        bt3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt3.setForeground(new java.awt.Color(0, 0, 153));
        bt3.setText("ISSUE");
        bt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt3MouseExited(evt);
            }
        });
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });

        bt4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt4.setForeground(new java.awt.Color(0, 0, 153));
        bt4.setText("CLOSE");
        bt4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt4MouseExited(evt);
            }
        });
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan2Layout = new javax.swing.GroupLayout(pan2);
        pan2.setLayout(pan2Layout);
        pan2Layout.setHorizontalGroup(
            pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pan2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pan2Layout.createSequentialGroup()
                        .addComponent(bt3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt4)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pan2Layout.setVerticalGroup(
            pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt4)
                    .addComponent(bt3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pan4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb3.setText("BOOK NO.     :");
        pan4.add(lb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 140, -1));

        lb4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb4.setText("BOOK NAME :");
        pan4.add(lb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 140, -1));

        tf6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pan4.add(tf6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 240, 30));

        lb5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb5.setText("AUTHOR No. :");
        pan4.add(lb5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 160, -1));

        lb6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb6.setText("SHELF No. :");
        pan4.add(lb6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 140, -1));

        lb7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb7.setText("PRICE :");
        pan4.add(lb7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 70, -1));

        lb8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb8.setText("PUBLISHER No. :");
        pan4.add(lb8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 180, -1));

        lb9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb9.setText("ALMIRAH No. :");
        pan4.add(lb9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 170, -1));

        tf5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tf5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tf5.setOpaque(true);
        pan4.add(tf5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 60, 30));

        lb10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb10.setText("STATUS  :");
        pan4.add(lb10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 90, -1));

        lb11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb11.setText("WHITEOFF :");
        pan4.add(lb11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 120, -1));

        tf7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tf7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tf7.setOpaque(true);
        pan4.add(tf7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 60, 30));

        tf11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pan4.add(tf11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 240, 30));

        tf12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pan4.add(tf12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 240, 30));

        tf13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pan4.add(tf13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 240, 30));

        tf9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tf9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tf9.setOpaque(true);
        pan4.add(tf9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 60, 30));

        tf10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tf10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tf10.setOpaque(true);
        pan4.add(tf10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 60, 30));

        tf8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tf8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tf8.setOpaque(true);
        pan4.add(tf8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 60, 30));

        lb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Nature7.jpg"))); // NOI18N
        pan4.add(lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 470));

        jScrollPane1.setViewportView(pan4);

        pan5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb12.setText("MEMBER  NO. :");
        pan5.add(lb12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 140, -1));

        lb2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb2.setText("MEMBER  NAME :");
        pan5.add(lb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 170, -1));

        tf15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pan5.add(tf15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 240, 30));

        lb13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb13.setText("e- mail :");
        pan5.add(lb13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 80, -1));

        lb14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb14.setText("STATUS :");
        pan5.add(lb14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 90, -1));

        tf19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pan5.add(tf19, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 240, 30));

        tf17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pan5.add(tf17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 240, 30));

        tf16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pan5.add(tf16, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 240, 30));

        tf18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pan5.add(tf18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 240, 30));

        lb15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb15.setText("MOBILE :");
        pan5.add(lb15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 90, -1));

        lb16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb16.setText("ADDRESS :");
        pan5.add(lb16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 110, -1));

        tf14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tf14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tf14.setOpaque(true);
        pan5.add(tf14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 60, 30));

        lb17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb17.setText("no. of book :");
        pan5.add(lb17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 110, -1));

        tf20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tf20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tf20.setOpaque(true);
        pan5.add(tf20, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 60, 30));

        lb1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Nature7.jpg"))); // NOI18N
        pan5.add(lb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 470));

        jScrollPane2.setViewportView(pan5);

        pan3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tf4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tf4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf4KeyTyped(evt);
            }
        });

        tf3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tf3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf3KeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Issue Date ");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Due Date");

        bt5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt5.setForeground(new java.awt.Color(0, 0, 153));
        bt5.setText("ISSUE");
        bt5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt5MouseExited(evt);
            }
        });
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });

        bt6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt6.setForeground(new java.awt.Color(0, 0, 153));
        bt6.setText("CLOSE");
        bt6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt6MouseExited(evt);
            }
        });
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });

        bt7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt7.setForeground(new java.awt.Color(0, 0, 153));
        bt7.setText("CLEAR");
        bt7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt7MouseExited(evt);
            }
        });
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan3Layout = new javax.swing.GroupLayout(pan3);
        pan3.setLayout(pan3Layout);
        pan3Layout.setHorizontalGroup(
            pan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan3Layout.createSequentialGroup()
                .addGroup(pan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(tf3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bt5)
                        .addGap(18, 18, 18)))
                .addGroup(pan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(pan3Layout.createSequentialGroup()
                        .addComponent(bt7)
                        .addGap(30, 30, 30)
                        .addComponent(bt6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pan3Layout.setVerticalGroup(
            pan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tf4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt5)
                    .addComponent(bt6)
                    .addComponent(bt7))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pan3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pan3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
        this.dispose();
        new Main().setVisible(true);
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        Connection con = null;
        ResultSet rs = null;
        Statement st = null;
        String sql = "";
        
        try
        {
             try
             {
                      Class.forName("java.sql.Driver");
                      con = DriverManager.getConnection(Login.URL,Login.URS,Login.PAS);
                      st = con.createStatement();
                      
                      sql = "select * from book where bno = "+tf1.getText()+";"; 
                      rs = st.executeQuery(sql);
                      
                      if(rs.next())
                      {
                          tf5.setText(rs.getObject(1)+"");
                          tf6.setText(rs.getObject(2)+"");
                          tf7.setText(rs.getObject(3)+"");
                          tf8.setText(rs.getObject(4)+"");
                          tf9.setText(rs.getObject(5)+"");
                          tf10.setText(rs.getObject(6)+"");
                          tf11.setText(rs.getObject(7)+"");
                          tf12.setText(rs.getObject(8)+"");
                          tf13.setText(rs.getObject(9)+"");
                      }
                      
                      if(tf12.getText().toUpperCase().trim().equals("N"))
                          JOptionPane.showMessageDialog(null,"BOOK IS ALREADY ISSUED ");
                      else  if(tf13.getText().toUpperCase().trim().equals("Y"))
                          JOptionPane.showMessageDialog(null,"BOOK IS NO LONGER PART OF LIBRARY !! ");
                      else
                      {
                          pan2.setVisible(true);
                          pan4.setVisible(true);
                      }
             }
             catch(Exception e)
             {
                  JOptionPane.showMessageDialog(null,"ERROR : "+e.getMessage());
             }
             finally
             {
                if(!con.isClosed())
                    con.close();
                if(!st.isClosed())
                    st.close();
                if(!rs.isClosed())
                   rs.close();
             }
        }
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null,"ERROR : "+e.getMessage());
        }
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
       this.dispose();
       new Main().setVisible(true);
    }//GEN-LAST:event_bt2ActionPerformed

    private int no_Book()
    {
        Connection con = null;
        ResultSet rs = null;
        Statement st = null;
        String sql = "";
        int x=0;
        
        try
        {
             try
             {
                      Class.forName("java.sql.Driver");
                      con = DriverManager.getConnection(Login.URL,Login.URS,Login.PAS);
                      st = con.createStatement();
                      
                      sql = "select bno from issue where mno = "+tf2.getText()+";"; 
                      rs = st.executeQuery(sql);
                      
                      if(rs.next())
                      {
                          x++;
                      }
                      
                      tf20.setText(x+"");
     
             }
             catch(Exception e)
             {
                  JOptionPane.showMessageDialog(null,"ERROR : "+e.getMessage());
             }
             finally
             {
                if(!con.isClosed())
                    con.close();
                if(!st.isClosed())
                    st.close();
                if(!rs.isClosed())
                   rs.close();
             }
        }
        catch(Exception e)
        {
                  JOptionPane.showMessageDialog(null,"ERROR : "+e.getMessage());
        }
        return x;
    }
        
    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        Connection con = null;
        ResultSet rs = null;
        Statement st = null;
        String sql = "";
        
        try
        {
             try
             {
                      Class.forName("java.sql.Driver");
                      con = DriverManager.getConnection(Login.URL,Login.URS,Login.PAS);
                      st = con.createStatement();
                      
                      sql = "select * from member where mno = "+tf2.getText()+";"; 
                      rs = st.executeQuery(sql);
                      
                      if(rs.next())
                      {
                          tf14.setText(rs.getObject(1)+"");
                          tf15.setText(rs.getObject(2)+"");
                          tf16.setText(rs.getObject(3)+"");
                          tf17.setText(rs.getObject(4)+"");
                          tf18.setText(rs.getObject(5)+"");
                          tf19.setText(rs.getObject(6)+"");
                      }
                      
                      if(tf19.getText().toUpperCase().trim().equals("N"))
                          JOptionPane.showMessageDialog(null,"MEMBERSHIP DENIED ");
                      else  if(no_Book()>3)
                          JOptionPane.showMessageDialog(null,"YOU HAVE ALREADY 3 BOOK !! ");
                      else
                      {
                          pan3.setVisible(true);
                          pan5.setVisible(true);
                      }
             }
             catch(Exception e)
             {
                  JOptionPane.showMessageDialog(null,"ERROR : "+e.getMessage());
             }
             finally
             {
                if(!con.isClosed())
                    con.close();
                if(!st.isClosed())
                    st.close();
                if(!rs.isClosed())
                   rs.close();
             }
        }
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null,"ERROR : "+e.getMessage());
        }
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        this.dispose();
        new Main().setVisible(true);
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        Connection con = null;
        Statement st = null;
        String sql = "";
        
        try
        {
             try
             {
                      Class.forName("java.sql.Driver");
                      con = DriverManager.getConnection(Login.URL,Login.URS,Login.PAS);
                      st = con.createStatement();
                      
                      sql = "insert into issue values("+tf1.getText()+","+tf2.getText()+",'"
                              +tf3.getText()+"','"+tf4.getText()+"');" ;
                      st.executeUpdate(sql);
                      
                      sql = "update book set status = 'N' where bno = "+tf1.getText()+";" ;
                      st.executeUpdate(sql);

                      JOptionPane.showMessageDialog(null,"BOOK ISSUE !!");
                      
                      pan2.setVisible(false);
                      pan3.setVisible(false);
                      pan4.setVisible(false);
                      pan5.setVisible(false);
                      tf1.setText("");
                      tf1.requestFocus();
             }
             catch(Exception e)
             {
                  JOptionPane.showMessageDialog(null,"ERROR : "+e.getMessage());
             }
             finally
             {
                if(!con.isClosed())
                    con.close();
                if(!st.isClosed())
                    st.close();
             }
        }
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null,"ERROR : "+e.getMessage());
        }
    }//GEN-LAST:event_bt5ActionPerformed

    private void tf1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf1KeyTyped
       char ch = evt.getKeyChar();
       if(ch=='\n')
       {
           bt1.doClick();
           tf2.requestFocus();
       }
    }//GEN-LAST:event_tf1KeyTyped

    private void tf2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf2KeyTyped
        char ch = evt.getKeyChar();
        if(ch=='\n')
           bt3.doClick();
    }//GEN-LAST:event_tf2KeyTyped

    private void tf3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf3KeyTyped
        char ch = evt.getKeyChar();
       if(ch=='\n')
           tf4.requestFocus();
    }//GEN-LAST:event_tf3KeyTyped

    private void tf4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf4KeyTyped
        char ch = evt.getKeyChar();
       if(ch=='\n')
           bt5.doClick();
    }//GEN-LAST:event_tf4KeyTyped

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
        
        tf3.setText("");
        tf4.setText("");
        tf3.requestFocus();
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt1MouseEntered
         bt1.setBackground(java.awt.Color.BLACK);
         bt1.setForeground(java.awt.Color.ORANGE);
    }//GEN-LAST:event_bt1MouseEntered

    private void bt1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt1MouseExited
        bt1.setBackground(java.awt.Color.WHITE);
        bt1.setForeground(java.awt.Color.BLUE);
    }//GEN-LAST:event_bt1MouseExited

    private void bt2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt2MouseExited
        bt2.setBackground(java.awt.Color.WHITE);
        bt2.setForeground(java.awt.Color.BLUE);        // TODO add your handling code here:
    }//GEN-LAST:event_bt2MouseExited

    private void bt3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt3MouseExited

        bt3.setBackground(java.awt.Color.WHITE);
        bt3.setForeground(java.awt.Color.BLUE);
    }//GEN-LAST:event_bt3MouseExited

    private void bt4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt4MouseExited

        bt4.setBackground(java.awt.Color.WHITE);
        bt4.setForeground(java.awt.Color.BLUE);
    }//GEN-LAST:event_bt4MouseExited

    private void bt5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt5MouseExited

        bt5.setBackground(java.awt.Color.WHITE);
        bt5.setForeground(java.awt.Color.BLUE);
    }//GEN-LAST:event_bt5MouseExited

    private void bt7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt7MouseEntered
         bt7.setBackground(java.awt.Color.BLACK);
         bt7.setForeground(java.awt.Color.ORANGE);
    }//GEN-LAST:event_bt7MouseEntered

    private void bt7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt7MouseExited
        bt7.setBackground(java.awt.Color.WHITE);
        bt7.setForeground(java.awt.Color.BLUE);
    }//GEN-LAST:event_bt7MouseExited

    private void bt2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt2MouseEntered
         bt2.setBackground(java.awt.Color.BLACK);
         bt2.setForeground(java.awt.Color.ORANGE);
    }//GEN-LAST:event_bt2MouseEntered

    private void bt3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt3MouseEntered

         bt3.setBackground(java.awt.Color.BLACK);
         bt3.setForeground(java.awt.Color.ORANGE);
    }//GEN-LAST:event_bt3MouseEntered

    private void bt4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt4MouseEntered

         bt4.setBackground(java.awt.Color.BLACK);
         bt4.setForeground(java.awt.Color.ORANGE);
    }//GEN-LAST:event_bt4MouseEntered

    private void bt5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt5MouseEntered
         bt5.setBackground(java.awt.Color.BLACK);
         bt5.setForeground(java.awt.Color.ORANGE);
    }//GEN-LAST:event_bt5MouseEntered

    private void bt6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt6MouseEntered
         bt6.setBackground(java.awt.Color.BLACK);
         bt6.setForeground(java.awt.Color.ORANGE);
    }//GEN-LAST:event_bt6MouseEntered

    private void bt6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt6MouseExited
        bt6.setBackground(java.awt.Color.WHITE);
        bt6.setForeground(java.awt.Color.BLUE);
    }//GEN-LAST:event_bt6MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb10;
    private javax.swing.JLabel lb11;
    private javax.swing.JLabel lb12;
    private javax.swing.JLabel lb13;
    private javax.swing.JLabel lb14;
    private javax.swing.JLabel lb15;
    private javax.swing.JLabel lb16;
    private javax.swing.JLabel lb17;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel lb6;
    private javax.swing.JLabel lb7;
    private javax.swing.JLabel lb8;
    private javax.swing.JLabel lb9;
    private javax.swing.JPanel pan1;
    private javax.swing.JPanel pan2;
    private javax.swing.JPanel pan3;
    private javax.swing.JPanel pan4;
    private javax.swing.JPanel pan5;
    private javax.swing.JTextField tf1;
    private javax.swing.JLabel tf10;
    private javax.swing.JTextField tf11;
    private javax.swing.JTextField tf12;
    private javax.swing.JTextField tf13;
    private javax.swing.JLabel tf14;
    private javax.swing.JTextField tf15;
    private javax.swing.JTextField tf16;
    private javax.swing.JTextField tf17;
    private javax.swing.JTextField tf18;
    private javax.swing.JTextField tf19;
    private javax.swing.JTextField tf2;
    private javax.swing.JLabel tf20;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JLabel tf5;
    private javax.swing.JTextField tf6;
    private javax.swing.JLabel tf7;
    private javax.swing.JLabel tf8;
    private javax.swing.JLabel tf9;
    // End of variables declaration//GEN-END:variables
}
