/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
import java.sql.*;
import javax.swing.JOptionPane;
public class Tr_Return extends javax.swing.JInternalFrame {

    /**
     * Creates new form Tr_Return
     */
    public Tr_Return() {
        initComponents();
        pan2.setVisible(false);
        pan3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        pan2 = new javax.swing.JPanel();
        tf2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pan3 = new javax.swing.JPanel();
        tf4 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bt5 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tf5 = new javax.swing.JTextField();
        bt8 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        bt10 = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));
        setTitle("RETURN FORM");

        pan1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Book No.");

        tf1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tf1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf1KeyTyped(evt);
            }
        });

        pan2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tf2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tf2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf2KeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Member No.");

        javax.swing.GroupLayout pan2Layout = new javax.swing.GroupLayout(pan2);
        pan2.setLayout(pan2Layout);
        pan2Layout.setHorizontalGroup(
            pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pan2Layout.setVerticalGroup(
            pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pan3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tf4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tf4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf4KeyTyped(evt);
            }
        });

        tf3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tf3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf3KeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Issue Date ");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Return Date");

        bt5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt5.setForeground(new java.awt.Color(0, 0, 153));
        bt5.setText("RETURN");
        bt5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt5MouseExited(evt);
            }
        });
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });

        bt6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt6.setForeground(new java.awt.Color(0, 0, 153));
        bt6.setText("CLOSE");
        bt6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt6MouseExited(evt);
            }
        });
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });

        bt7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt7.setForeground(new java.awt.Color(0, 0, 153));
        bt7.setText("CLEAR");
        bt7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt7MouseExited(evt);
            }
        });
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Fine");

        tf5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tf5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf5KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pan3Layout = new javax.swing.GroupLayout(pan3);
        pan3.setLayout(pan3Layout);
        pan3Layout.setHorizontalGroup(
            pan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan3Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(bt5)
                .addGap(18, 18, 18)
                .addComponent(bt7)
                .addGap(18, 18, 18)
                .addComponent(bt6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pan3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(pan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(tf5, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pan3Layout.createSequentialGroup()
                        .addComponent(tf3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pan3Layout.setVerticalGroup(
            pan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tf4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(pan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt5)
                    .addComponent(bt7)
                    .addComponent(bt6))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        bt8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt8.setForeground(new java.awt.Color(0, 0, 153));
        bt8.setText("RETURN");
        bt8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt8MouseExited(evt);
            }
        });
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });

        bt9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt9.setForeground(new java.awt.Color(0, 0, 153));
        bt9.setText("CLEAR");
        bt9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt9MouseExited(evt);
            }
        });
        bt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt9ActionPerformed(evt);
            }
        });

        bt10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt10.setForeground(new java.awt.Color(0, 0, 153));
        bt10.setText("CLOSE");
        bt10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt10MouseExited(evt);
            }
        });
        bt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan1Layout = new javax.swing.GroupLayout(pan1);
        pan1.setLayout(pan1Layout);
        pan1Layout.setHorizontalGroup(
            pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan1Layout.createSequentialGroup()
                .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pan1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(pan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pan1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(bt8)
                        .addGap(18, 18, 18)
                        .addComponent(bt9)
                        .addGap(18, 18, 18)
                        .addComponent(bt10))
                    .addGroup(pan1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(pan3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        pan1Layout.setVerticalGroup(
            pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt8)
                    .addComponent(bt10)
                    .addComponent(bt9))
                .addGap(18, 18, 18)
                .addComponent(pan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pan3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(pan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(pan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf1KeyTyped
        char ch = evt.getKeyChar();
        if(ch=='\n')
        {
            bt8.doClick();
            tf2.requestFocus();
        }
    }//GEN-LAST:event_tf1KeyTyped

    private void tf2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf2KeyTyped
        char ch = evt.getKeyChar();
        if(ch=='\n')
        {
            tf3.requestFocus();
        }
    }//GEN-LAST:event_tf2KeyTyped

    private void tf4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf4KeyTyped
        char ch = evt.getKeyChar();
        if(ch=='\n')
            tf5.requestFocus();
    }//GEN-LAST:event_tf4KeyTyped

    private void tf3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf3KeyTyped
        char ch = evt.getKeyChar();
        if(ch=='\n')
            tf4.requestFocus();
    }//GEN-LAST:event_tf3KeyTyped

    private void bt5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt5MouseEntered
        bt5.setBackground(java.awt.Color.BLACK);
        bt5.setForeground(java.awt.Color.ORANGE);
    }//GEN-LAST:event_bt5MouseEntered

    private void bt5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt5MouseExited

        bt5.setBackground(java.awt.Color.WHITE);
        bt5.setForeground(java.awt.Color.BLUE);
    }//GEN-LAST:event_bt5MouseExited

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed

        Connection con = null;
        Statement st = null;
        String sql = "";

        try
        {
            try
            {
                Class.forName("java.sql.Driver");
                con = DriverManager.getConnection(Login.URL,Login.URS,Login.PAS);
                st = con.createStatement();

                sql = "insert into history values("+tf1.getText()+","+tf2.getText()+",'"
                +tf3.getText()+"','"+tf4.getText()+"',"+tf5.getText()+");" ;
                st.executeUpdate(sql);

                sql = "update book set status = 'Y' where bno = "+tf1.getText()+";" ;
                st.executeUpdate(sql);
                
                sql = "delete from issue where bno = "+tf1.getText()+";" ;
                st.executeUpdate(sql);

                JOptionPane.showMessageDialog(null,"BOOK RETURN !!");

                pan2.setVisible(false);
                pan3.setVisible(false);
                tf1.setText("");
                tf1.requestFocus();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"ERROR : "+e.getMessage());
            }
            finally
            {
                if(!con.isClosed())
                con.close();
                if(!st.isClosed())
                st.close();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"ERROR : "+e.getMessage());
        }
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt6MouseEntered
        bt6.setBackground(java.awt.Color.BLACK);
        bt6.setForeground(java.awt.Color.ORANGE);
    }//GEN-LAST:event_bt6MouseEntered

    private void bt6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt6MouseExited
        bt6.setBackground(java.awt.Color.WHITE);
        bt6.setForeground(java.awt.Color.BLUE);
    }//GEN-LAST:event_bt6MouseExited

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
        this.dispose();
        new Main().setVisible(true);
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt7MouseEntered
        bt7.setBackground(java.awt.Color.BLACK);
        bt7.setForeground(java.awt.Color.ORANGE);
    }//GEN-LAST:event_bt7MouseEntered

    private void bt7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt7MouseExited
        bt7.setBackground(java.awt.Color.WHITE);
        bt7.setForeground(java.awt.Color.BLUE);
    }//GEN-LAST:event_bt7MouseExited

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed

        tf3.setText("");
        tf4.setText("");
        tf5.setText("");
        tf3.requestFocus();
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt8MouseEntered
        bt8.setBackground(java.awt.Color.BLACK);
        bt8.setForeground(java.awt.Color.ORANGE);
    }//GEN-LAST:event_bt8MouseEntered

    private void bt8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt8MouseExited
        bt8.setBackground(java.awt.Color.WHITE);
        bt8.setForeground(java.awt.Color.BLUE);
    }//GEN-LAST:event_bt8MouseExited

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
 
       Connection con = null;
       ResultSet rs = null;
       Statement st = null ;
       String sql = "";
       
       try
       {
           try
           {
                  Class.forName("java.sql.Driver");
                  con = DriverManager.getConnection(Login.URL,Login.URS,Login.PAS);
                  st = con.createStatement();
                  
                  sql = "Select * from issue where bno = "+tf1.getText()+";";
                  rs = st.executeQuery(sql);
                  
                  if(rs.next())
                  {
                        tf1.setText(rs.getInt(1)+"");
                        tf2.setText(rs.getObject(2)+"");
                        tf3.setText(rs.getObject(3)+"");
                        tf4.setText(rs.getObject(4)+"");       
                        pan2.setVisible(true);
                        pan3.setVisible(true);
                  }
                  else
                      JOptionPane.showMessageDialog(null,"BOOK IS NOT ISSUED !!");
           }
           catch(Exception e)
           {
                  JOptionPane.showMessageDialog(null,"ERROR : "+e.getMessage());
           }
           finally
            {
                 if(!con.isClosed())
                     con.close();
                 if(!st.isClosed())
                     st.close();
                 if(!rs.isClosed())
                     rs.close();
            }
       }
       catch(Exception e)
       {
             JOptionPane.showMessageDialog(null,"ERROR : "+e.getMessage());
       }
    }//GEN-LAST:event_bt8ActionPerformed

    private void bt9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt9MouseEntered
         bt9.setBackground(java.awt.Color.BLACK);
         bt9.setForeground(java.awt.Color.ORANGE);
    }//GEN-LAST:event_bt9MouseEntered

    private void bt9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt9MouseExited
        bt9.setBackground(java.awt.Color.WHITE);
        bt9.setForeground(java.awt.Color.BLUE);
    }//GEN-LAST:event_bt9MouseExited

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
        tf1.setText("");
        tf1.requestFocus();
    }//GEN-LAST:event_bt9ActionPerformed

    private void bt10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt10MouseEntered
         bt10.setBackground(java.awt.Color.BLACK);
         bt10.setForeground(java.awt.Color.ORANGE);
    }//GEN-LAST:event_bt10MouseEntered

    private void bt10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt10MouseExited
        bt10.setBackground(java.awt.Color.WHITE);
        bt10.setForeground(java.awt.Color.BLUE);
    }//GEN-LAST:event_bt10MouseExited

    private void bt10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt10ActionPerformed
        this.dispose();
        new Main().setVisible(true);
    }//GEN-LAST:event_bt10ActionPerformed

    private void tf5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf5KeyTyped
       char ch =evt.getKeyChar();
       if(ch=='\n')
           bt5.doClick();
    }//GEN-LAST:event_tf5KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt10;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel pan1;
    private javax.swing.JPanel pan2;
    private javax.swing.JPanel pan3;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    // End of variables declaration//GEN-END:variables
}
